on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/mysql@v1
      with:
        connection-string: ${{ secrets.DAEUNYIM_GH_FLEXIBLESERVERDB_MYSQL_CONNECTION_STRING
          }}
        server-name: daeunyim-gh.mysql.database.azure.com
        sql-file: ./scripts/postgres_sample.sql
