on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - uses: azure/postgresql@v1
      with:
        connection-string: "${{\u202Fsecrets.AZURE_POSTGRESQL_CONNECTION_STRING }}"
        plsql-file: '''pg_schema.sql'''
        server-name: '''daeunyim-pg-test.postgres.database.azure.com'''
